### ISSUE TITLE
Github actions 실행 시 에러

### ISSUE THREAD

**Issue by NCookies** [NCookies/imad-server#130]
아래와 같은 메세지를 뱉어내면서 에러 발생

```
3 actionable tasks: 2 executed, 1 up-to-date
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processResources'.
> Entry application-aws.yml is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.6.1/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

* Try:
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':processResources'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:140)
...
```

**Comment by NCookies** [comment]
`build.gradle` 파일에 아래 코드 추가하여 해결

```gradle
tasks {
	processResources {
		duplicatesStrategy = DuplicatesStrategy.INCLUDE
	}
}
```

https://derveljunit.tistory.com/336 참고
